# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'index.md'
toggles
  features:
    # Include code to build the graph view per page 
    graph:
      enabled: False
