name: Daily Make Update

on: 
  workflow_dispatch: # This allows manual execution of the workflow.
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC.

jobs:
  update:
    runs-on: ubuntu-latest # Ubuntu is generally faster and more cost-efficient for GitHub to run, making it the default choice. For most projects, Linux (Ubuntu) will work just fine even if developed on macOS.

    steps:
      # Step 1: Download the GitHub repository’s source code to the runner (the virtual machine where the action is being executed). Without this step, the subsequent steps wouldn't have access to the repository's code.
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true  # This will initialize and update submodules.
          fetch-depth: 0 # Ensures that all commit history is fetched. Sometimes, a shallow clone can cause issues with submodules, so this ensures that full commit history is available for both the main repository and submodules.
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use personal access token, to enable private repository access, created in 'developer settings' and referenced in 'secrets and variables' of this repository.
    
      - name: Set up Git user name and email to allow push in subsequent step.
        run: |
          git config --local user.name "Arthur Tainmont"
          git config --local user.email "tainmontarthur@icloud.com"

      # Step 2: Run 'make update' to update the obsidian repository and push.
      - name: Run make update
        run: make update
